spring:
  application:
    name: zp-datasharing-module
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        group: zp
        server-addr: 127.0.0.1:8848
        namespace: 123
        username: nacos
        password: 123
        file-extension: yml
      discovery:
        group: zp
        server-addr: 127.0.0.1:8848
        namespace: 123
        username: nacos
        password: 123
        ip: 127.0.0.1
    openfeign:
      lazy-attributes-resolution: true
      compression:
        request:
          enabled: true
        response:
          enabled:  true

    sentinel:
      enabled: false

  config:
    import:
      - optional:nacos:zp-mysql-config.yml?group=zp
      - optional:nacos:zp-redis-config.yml?group=zp
      - optional:nacos:zp-config?group=zp
      - optional:nacos:zp-actuator-config.yml?group=zp
      - optional:nacos:zp-mvc-normal?group=zp
      - optional:nacos:zp-rabbit-config?group=zp


server:
  port: 7051
  compression:
    enabled: true


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


