spring:
  application:
    name: zp-base-module
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        group: zp
        server-addr: 1:8848
        namespace: 1
        username: 1
        password: 1
        file-extension: yml
      discovery:
        group: zp
        server-addr: 1
        namespace: 1
        username: 1
        password: 1
        ip: 127.0.0.1
    openfeign:
      lazy-attributes-resolution: true
      compression:
        request:
          enabled: true
        response:
          enabled:  true
      okhttp:
        enabled: true


  config:
    import:
      - optional:nacos:zp-mysql-config.yml?group=zp
      - optional:nacos:zp-redis-config.yml?group=zp
      - optional:nacos:zp-rabbit-config?group=zp
      - optional:nacos:zp-config?group=zp
      - optional:nacos:zp-actuator-config.yml?group=zp
      - optional:nacos:zp-mvc-normal?group=zp




server:
  port: 6050
  compression:
    enabled: true


